### ISSUE TITLE
More complex detection condition logic

### ISSUE THREAD

**Issue by AMDmi3** [Donatallo/donatallo-database#8]
For now, we only support OR logic for detection conditions. We may need AND logic as in "opsys=Linux AND /etc/gentoo-release file present". From syntax standpoint, either simple `detection-and:` alternative to `detection:`, or nested constructs as in

```
detection:
  - and
    - file-in-etc: gentoo-release
    - or
      - opsys: Linux
      - uname-s: Linux
```
